### ISSUE TITLE
 [1]  Audit HTTP Methods  is giving error

### ISSUE THREAD

**Issue by Geekuserr** [haroonawanofficial/Tishna-Automated-Web-Application-Hacker#1]
I am testing on Kali Linux 2018.4 amd64. Installation was successful but when i run the 1st option it is giving error

tishna: _>  http://testphp.vulnweb.com

Missing base argument at /usr/share/perl5/HTTP/Response.pm line 99.

**Comment by pawp81** [comment]
Same here.

**Comment by SemilutTuran** [comment]
The same here

**Comment by haroonawanofficial** [comment]
Yes there is typo error. I checked also there is one file missing for form based xss. Clone in few hours, issue will be fixed.

**Comment by pawp81** [comment]
I cloned it today and got the same error: 
Missing base argument at /usr/share/perl5/HTTP/Response.pm line 99.

**Comment by haroonawanofficial** [comment]
clone again fixed.
