### ISSUE TITLE
Starting Tishna

### ISSUE THREAD

**Issue by pawp81** [haroonawanofficial/Tishna-Automated-Web-Application-Hacker#2]
It would be good to add to readme.md information how to start Tishna after installation

**Comment by xin3c** [comment]
just type " perl tishna.pl " in tishna directory. This is a natural selection for not smart enough i think

**Comment by haroonawanofficial** [comment]
Type Tishna or tishna, depending on the installation in anywhere in system, software will run

**Comment by haroonawanofficial** [comment]
confirm?
