### ISSUE TITLE
how can i remove broken installation, or tishna completely?

### ISSUE THREAD

**Issue by vactum0** [haroonawanofficial/Tishna-Automated-Web-Application-Hacker#3]
while installing again (./Kali_Installer.sh), getting this error
"If You Want To Install You Must Remove Previous Installations"

while running tishna (by typing "tishna"), getting this error
Can't locate IO/Socket/SecureSocks.pm in @INC (you may need to install the IO::Socket::SecureSocks module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/tishna/tishna.pl line 1689.
BEGIN failed--compilation aborted at /usr/share/tishna/tishna.pl line 1689.

I manually interrupt the installation yesterday, due to internet connectivity
& is it necessary to install it by root?

**Comment by haroonawanofficial** [comment]
This is not something serious, it's dependencies error.  Try this
cpan -fi IO::Socket::SecureSocks

You can install it without root rewuirements, sudo command will ask password when you install provide it.

**Comment by vactum0** [comment]
First of all thank you,
now I'm getting this error
Can't locate Net/SSLeay.pm in @INC (you may need to install the Net::SSLeay module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/local/share/perl/5.30.0/IO/Socket/SSL.pm line 19.
BEGIN failed--compilation aborted at /usr/local/share/perl/5.30.0/IO/Socket/SSL.pm line 19.
Compilation failed in require at /usr/local/share/perl/5.30.0/IO/Socket/SecureSocks.pm line 10.
Compilation failed in require at /usr/share/tishna/tishna.pl line 1689.
BEGIN failed--compilation aborted at /usr/share/tishna/tishna.pl line 1689.

I know I can install this with cpan also, but I'll have to install all dependencies manually one by one due to broken installation, as I told u that I interrupted the installation.
So, is there any way to remove previous installation completely?
so then I'll clean install it again

**Comment by haroonawanofficial** [comment]
Yes I'm making uninstaller, I will post it here. I will let you know then simply run uninstaller than installer.

**Comment by vactum0** [comment]
Thanks a lot

**Comment by haroonawanofficial** [comment]
try Uninstaller.sh, it should work after it finishes, reboot and try clean installer again.

Confirm?

**Comment by vactum0** [comment]
okay, lmt

**Comment by vactum0** [comment]
I don't knwo why I'm getting 
"line 114: syntax error: unexpected end of file"

**Comment by haroonawanofficial** [comment]
No issue, try again, I fixed it

**Comment by vactum0** [comment]
Thank you :)

Word of CAUTION for Readers: Don't run installer outside the folder
