### ISSUE TITLE
Cross Site Request Forgery Audit Toolkit module doesn't works

### ISSUE THREAD

**Issue by cristianbarbaro** [haroonawanofficial/Tishna-Automated-Web-Application-Hacker#5]
Hello, I am testing application modules and I found an error in module 18 (Cross Site Request Forgery Audit Toolkit) where the file `xsrfprobe.py` is not found after executing it.

Attached image of issue.

![image](https://user-images.githubusercontent.com/7277401/72103769-aa693d00-3308-11ea-96cb-44040d0f611a.png)

Regards

**Comment by haroonawanofficial** [comment]
It was typo error, download xsrfprobe.sh, and put it in directory or simple copy paste new content of xsrfprobe.sh then python will run it. 

Thanks for notifying!
