### ISSUE TITLE
Option 7, missing file

### ISSUE THREAD

**Issue by vactum0** [haroonawanofficial/Tishna-Automated-Web-Application-Hacker#6]
I was trying option 7
"[7]  Find XSS in Forms Simple Attack"
but getting this 
![image](https://user-images.githubusercontent.com/29106305/72130963-c1f20580-339c-11ea-95ce-564e90d852f0.png)

Kindly tell me that in what folder should I move xss.sh file?

**Comment by haroonawanofficial** [comment]
It's not this file, I forgot to upload another file. I will do it few hours

**Comment by haroonawanofficial** [comment]
I double checked it, xss.sh is present along with pattern file, you should simple do chmod u+x *.sh and chmod -R 755 Tishna-Automated-Web-Application-Hacker/

it should fix it

**Comment by haroonawanofficial** [comment]
Clone from here if u see any file missing

**Comment by vactum0** [comment]
You are right, all files are present at there position
![Screenshot (109)](https://user-images.githubusercontent.com/29106305/72213360-9ba0a700-350f-11ea-801a-a92850c833d7.png)
maybe error was due to wrong parameter 
![Screenshot (110)](https://user-images.githubusercontent.com/29106305/72213427-89733880-3510-11ea-9f3e-89c5a1054f49.png)
 
Thanks a lot :)
