### ISSUE TITLE
Missing file option 54 RFI

### ISSUE THREAD

**Issue by cristianbarbaro** [haroonawanofficial/Tishna-Automated-Web-Application-Hacker#7]
When executing option 54 (RFI) I get an error.
When I run `rfi.sh` it informs me that the `rfi.pl` script does not exist.

![image](https://user-images.githubusercontent.com/7277401/72150855-6405f380-3385-11ea-914b-2d223126a0b9.png)

![image](https://user-images.githubusercontent.com/7277401/72150882-6ec08880-3385-11ea-90ce-50ef88d41104.png)

**Comment by haroonawanofficial** [comment]
Fixed. It was missing
