### ISSUE TITLE
[False Positive] file missing error in Option 6

### ISSUE THREAD

**Issue by vactum0** [haroonawanofficial/Tishna-Automated-Web-Application-Hacker#8]
Even though file is present, but I'm getting this
![Screenshot (114)](https://user-images.githubusercontent.com/29106305/72215469-bcc7be80-3534-11ea-94d0-09136b06ac9f.png)

I have tested in 2 different OS
![image](https://user-images.githubusercontent.com/29106305/72215511-2942bd80-3535-11ea-97f0-7e917ce056e2.png)

Not related to 'permission/privilege' error
![image](https://user-images.githubusercontent.com/29106305/72215526-5a22f280-3535-11ea-9020-e73cccee95fe.png)

**Comment by haroonawanofficial** [comment]
You should put config.xml in root directory. You should clone from here. It have all files.  Put config.xml with your own payloads and many are built in into /root/ folder

**Comment by vactum0** [comment]
I used this to clone 
"git clone https://github.com/haroonawanofficial/Tishna.git"  

should I use this?
"git clone https://github.com/haroonawanofficial/Tishna-Automated-Web-Application-Hacker.git" 

I think that solution is pretty simple,
since I installed tishna in root account, therefore all files are in /root/Tishna , instead of /home/

![image](https://user-images.githubusercontent.com/29106305/72216818-e76f4280-3547-11ea-882f-75e46c883958.png)

This script should look for files in /root/Tishna instead of /home/
OR
/home/*user_name*/Tishna      (For non root users)

**Comment by haroonawanofficial** [comment]
This is typo error as I was updating it. It should be in root/ folder not home/. I fix it in few hours.

**Comment by vactum0** [comment]
Thank you :)

**Comment by haroonawanofficial** [comment]
fixed. now copy your file into /root/ folder, you can also edit your own payloads. old school to modern to latest for waf baypass payloads, all will work.

**Comment by haroonawanofficial** [comment]
Refer to this video, for option 6

https://www.facebook.com/plugins/video.php?href=https%3A%2F%2Fwww.facebook.com%2Fofficialharoonawan%2Fvideos%2F314089446174379%2F

**Comment by vactum0** [comment]
can I change the required path for config.xml from '/root/' to '/root/Tishna' locally?
because, since, all files are already present there therefore it should also fetch payloads from that repo. folder. 
Only for ease and clean look (I'm on terminal)
